### ISSUE TITLE
Explanation of capabilities

### ISSUE THREAD

**Issue by kyeshmz** [GregoryConrad/mimir#171]
Hi, just wanted to clarify if I can do the same things that millisearch does such as parse CJK in this package?
If so, I think it would be a much greater option to what is available in other SQL libraries.

Also would like to know if you think this library is production ready or if there are glaring issues right now

**Comment by GregoryConrad** [comment]
Hi!

> Hi, just wanted to clarify if I can do the same things that millisearch does such as parse CJK in this package?

You should be able to (as in, it should *just work* without any extra configuration), but I haven't explicitly tested it. If you try it, please let me know the results!

> Also would like to know if you think this library is production ready or if there are glaring issues right now

While mimir is still in `dev` releases, don't ship to production. The main blocking issue right now is waiting for Meilisearch v1.2.0 to be released. Once it is released, I plan on marking mimir as stable. I was originally waiting on v1.1.0, which was released a couple days ago, but unfortunately I had to make a PR to meilisearch in order to fix #156, which is pushing a stable release back a bit.

That being said, every platform (other than Android) should be working fine right now. I thought Android was OK since mimir worked on the pixel devices I tested on, but #170 was just raised yesterday and I want to tackle that before marking mimir as stable.

**Comment by GregoryConrad** [comment]
Actually going to re-open this until I update the documentation with this info

**Comment by kyeshmz** [comment]
Thanks for the quick turn around!
I will look into this as it seems like a nice drop in to many of the things meilisearch is able to provide.
And it is something other libaries struggle with such as with isar [#1135](https://github.com/isar/isar/issues/1135)

**Comment by GregoryConrad** [comment]
Update README with applicable information (CJK is supported in mimir)

**Comment by kyeshmz** [comment]
Just want to say, this package works exceptionally well without fail even in CJK languages, thank you!
