### ISSUE TITLE
Can't get instance.

### ISSUE THREAD

**Issue by AndriyChaban** [GregoryConrad/mimir#188]
on the initial Mimir.getInstance command I should provide libembedded_milli.so file. However, can't find it anywhere.
Pretty sure this is not the issue in package. But, unfortunately, cannot solve it by myself. On the readme page no info on that.

**Comment by GregoryConrad** [comment]
@AndriyChaban Are you using Flutter, or Dart-only?

**Comment by AndriyChaban** [comment]
I tried both. In flutter the command Mimir.getDefaultInstance throws above mentioned error.
Tried with dart-only all getInstance variants too. Asks the path to that file.

**Comment by GregoryConrad** [comment]
@AndriyChaban If you are using Flutter, you should be using one of the [methods mentioned here](https://pub.dev/documentation/flutter_mimir/latest/flutter_mimir/FlutterMimirInterface.html):
1. `Mimir.defaultInstance` for 99.9% of use cases
2. `Mimir.getInstanceForName` for when you need another instance for some reason, but in the default location
3. `Mimir.getInstanceForPath` for when you need to override the entire path of the database

You *should not* being using `getInstance` directly in Flutter.

> throws above mentioned error

You didn't really provide any error details (i.e., device, stack trace, etc.); would you mind sharing them please (assuming you used one of the 3 methods listed directly above)?

**Comment by GregoryConrad** [comment]
@AndriyChaban I'm guessing you are using Android/Linux then, in which case the `.so` file probably failed to download when you were building the project. Delete any build output folders (like `build/`) and run `flutter clean`. Even better, if you are using git, something like `git clean -xfd` would work well (but take a look at what that does before blindly running it!).

Note: until Dart releases "native assets", you will need a semi-decent Internet connection in order to build projects using mimir (and it might take a few minutes to download the necessary binaries). Unfortunately, there is nothing I can do about that at the moment.

**Comment by AndriyChaban** [comment]
Thank you for prompt replies. Maybe my mobile internet speed does not comply with the requirements of 'semi-decent Internet connection' category... 
Will try later again.

**Comment by GregoryConrad** [comment]
Closing this as it is highly likely that you just need to clean your Flutter/Dart build cache for Android and retry (and if you have a flaky Internet connection, it may take a few tries).
