### ISSUE TITLE
Example should not depend on other packages

### ISSUE THREAD

**Issue by kyeshmz** [GregoryConrad/mimir#237]
Hi, I just looked into the example and it seems to utilize rearch, another one of your packages.
I am not really in the liberty to judge how your repository should work, but it might put off people to using this package, especially while using a undocumented one.

**Comment by GregoryConrad** [comment]
I originally started to write the example in vanilla Flutter but quickly realized how much of a pain it is. Quickly switched it to Riverpod + hooks for a bit, but those have their own problems.

Didn't actually expect anyone to take too much of a look at the example here yet (mimir is still relatively new), but you can find all of the mimir-specific code in the first ~50 lines of code in `main.dart`. Not much is going on there--essentially just opening an index and then triggering a `searchStream` on it:
```dart
final instance = await Mimir.defaultInstance;
final index = instance.getIndex('movies');

// Add all the documents asynchronously.
await rootBundle
    .loadString('assets/tmdb_movies.json')
    .then((l) => json.decode(l) as List)
    .then((l) => l.cast<Map<String, dynamic>>())
    .then(index.setDocuments);

// ...

index.searchStream(query: query.$1)
```
That's about it; the rest is just UI and glue, which is out of the scope of what mimir does.

> especially while using a undocumented one.

Absolutely agree, but rearch is also currently pre-release (it's the topic of my master's thesis) and I frankly didn't expect anyone to look at it yet. Essentially the only reason it's published right now is to reserve the name and also so my thesis advisor can more easily play around with it. I did jump the gun and convert this package to use rearch before formal release, but that is mostly because:
- I wanted the new gif that you can see in the README, and that required a rewrite (the old version with riverpod was not as clean)
- The old version gave me issues in integration tests from time to time (that's not Riverpod's fault though, just a poorly-written integration test that I rewrote alongside the example app)

All that being said, I have full documentation coming out for it at some point within the next couple months when I release rearch, so this won't be an issue for too much longer.

Closing this as I don't plan on rewriting the example, but thank you for the feedback!

**Comment by kyeshmz** [comment]
More power to you, as your the author of the package

> Riverpod + hooks for a bit, but those have their own problems.

Can you elaborate on this? Just wanted to know what some of the pains were

**Comment by GregoryConrad** [comment]
> Can you elaborate on this? Just wanted to know what some of the pains were

I just made the rearch Dart implementation public (it's still pre-release though); and there is a section in [the README](https://github.com/GregoryConrad/rearch-dart#why-not-riverpod) detailing some of the issues I've found with Riverpod and hooks.
