### ISSUE TITLE
Switch IOS and MacOs To Use Dynamic Libs

### ISSUE THREAD

**Issue by mcmah309** [GregoryConrad/mimir#334]
Due to difficulties with CocoaPods, IOS and MacOs currently use discouraged `ExternalLibrary.process`. Flutter `3.24.0` provides support for the Swift Package Manager that may fix these issues: https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-plugin-authors#how-to-add-swift-package-manager-support-to-an-existing-flutter-plugin

Ref: https://github.com/GregoryConrad/mimir/pull/332#issuecomment-2259444095

**Comment by GregoryConrad** [comment]
Oh! Thanks for the heads up; I had no clue SPM support was right around the corner. I'll take a look later today.

**Comment by GregoryConrad** [comment]
I _almost_ got really lucky with this since SPM has support for remote binary targets. Only problem is that they require a `checksum` for it, which is not feasible for me to do based on how Mimir is setup. Mimir needs to generate the changes to OS build specific files (like `package.swift`) when a new version is created, but the new version being created won't have the binaries generated in CI until the new version is created and has been pushed to GitHub (and thus no checksum until after the fact).

So that leaves us with either:
- Seeing if SPM can support compiling the Rust code itself (if it isn't too much of a PITA)
- Download the file ourselves and then just use the local file for the binary target

I'm going to look into the first option to start, but will fallback to the second in case the first isn't feasible.

**Comment by GregoryConrad** [comment]
Just realized I won't be able to do the Rust build on local dev machines since the Rust code lives in `/packages/mimir`, not `/packages/flutter_mimir`. So I'll need to just write a hack in the `package.swift` to download the binary file, much like it is done in CocoaPods today.

**Comment by GregoryConrad** [comment]
TODO: update FRB code gen settings for SPM (disable or move C headers to new location)

**Comment by GregoryConrad** [comment]
...and SPM runs in a sandbox so I've gotta completely redo CI/CD so that we can generate a checksum ahead of time. Not super happy about it, but what can you do

**Comment by GregoryConrad** [comment]
I've since realized this will just be too much of a pain to do with all of the changes needed. I'm holding out hope that [Native Assets](https://github.com/dart-lang/sdk/issues/50565) will come before CocoaPods support is removed.
