### ISSUE TITLE
Autogenerate the document `Id`s

### ISSUE THREAD

**Issue by irevoire** [GregoryConrad/mimir#75]
Hey, I was looking at your README. The project looks really cool!
I was just wondering about this part in the important caveats:

Document ids:
    - Documents without an id field will have one autogenerated (out of necessity)
        - I would recommend adding an id field to your documents when possible though
    - Current bug in milli: you need your id field at the top of your documents
        See https://github.com/meilisearch/product/discussions/206 for more

From what I understand, Mimir is going to check if there is already an `id` in the documents, and if the document doesn't have one, then it's going to autogenerate an id.
Thus, in any case, your primary key is going to be `id`. Why don't you just specify it to meilisearch, so it doesn't try to infer anything?

**Comment by GregoryConrad** [comment]
Hi @irevoire 👋

That tidbit in the README is actually just about how milli handles the documents internally when using `autogenerate_docids: true` (which mimir uses) so that users of this library will know how document ids are handled. At the moment, this project just wraps around a lot of the functionality in milli directly, providing Dart-idiomatic APIs where it makes sense. This is one of those cases; I leave the PK/id inference up to milli.

For a temporary workaround, I could just modify the JSON users supply and pass that modified JSON on over to milli, except considering this project is still in alpha status and I can just upgrade the milli to `1.0` when it comes out (hopefully soon), I haven't bothered.

**Comment by irevoire** [comment]
Ah ok, fyi you should be super cautious with the `autogenerate_docids` feature isn't really tested anywhere currently. That's why it's not exposed in meilisearch. It has been here for more than a year now, and we never took the time to fully design it in terms of product; thus, I don't really know how it works when it encounters some strange «edge case».
This may be one of the cases where it's better actually to handle it yourself in your SDK :grimacing:

**Comment by GregoryConrad** [comment]
Thanks for the heads up! I will add that to my TODOs.

**Comment by GregoryConrad** [comment]
Closing as a won't fix because I want users to explicitly pass in an `id` so methods that depend on it are predictable.
